### ISSUE TITLE
Add Support for 5v5 GameMode

### ISSUE THREAD

**Issue by Nostrademous** [TimZaman/dotaclient#11]
All Pick Support - DOTA_GAMEMODE_AP

**Comment by TimZaman** [comment]
That's supported already right in the proto no?

**Comment by TimZaman** [comment]
I think that should already work?

**Comment by TimZaman** [comment]
This should be straightforward. We would only need to provide a (static) configuration that tells the game which bots to configure. Right now that's hack-hardcoded in https://github.com/TimZaman/dotaservice/blob/master/dotaservice/lua/bot_generic.lua#L146-L148

**Comment by TimZaman** [comment]
Done!
