### ISSUE TITLE
Movements: MoveToPosition?

### ISSUE THREAD

**Issue by TimZaman** [TimZaman/dotaclient#25]
I now found `MoveToPosition` too, @Nostrademous . How's that different?

**Comment by TimZaman** [comment]
Scrolling through all the ways of making the hero move, because it seems
(not sure!) the hero doesnt move _exactly_.

**Comment by Nostrademous** [comment]
Oh... Move To Location is Move To Position AFAIK (they changed the name)

The Move Functions are:

* MoveToLocation
* MoveToUnit
* MoveDirectly
* MovePath (takes a table of waypoints)
* AttackMove
