### ISSUE TITLE
PPO Improvements

### ISSUE THREAD

**Issue by Nostrademous** [TimZaman/dotaclient#31]
https://arxiv.org/abs/1901.10314

**Comment by TimZaman** [comment]
oh dude you stay on top of things! :)

**Comment by TimZaman** [comment]
Hmm I wonder if the paper is entirely valid, not sure how it relates to exploration. PPO is just PO with conservative updates.

**Comment by TimZaman** [comment]
I'll wait until time shows (others) confirm this paper is awesome.
